[package]
name = "api_crud_artix_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
diesel = { version = "2.2.0", features = ["mysql"] }
config = "0.14.0"
dotenv = "0.15.0"
serde = { version = "1.0.203", features = ["derive"] }
